name: EKS Cluster Auto Scaling

on:
  schedule:
    # Monday at 7am - Scale out
    - cron: '0 7 * * 1'
    # Friday at 8pm - Scale in
    - cron: '0 20 * * 5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-scaling-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: feature/control-plane-ops
          # Make sure to fetch with sufficient depth for history
          fetch-depth: 0
          # Use PAT for checkout
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set scaling parameters based on day and time
        id: set-scaling
        run: |
          # Get current day of week (1-7, where 1 is Monday)
          DAY=$(date +%u)
          # Get current hour (0-23)
          HOUR=$(date +%H)
          
          # For testing purposes, determine operation based on workflow_dispatch or schedule
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Allow manual selection via input when manually triggered
            OPERATION="${{ github.event.inputs.operation || 'scale-out' }}"
          else
            # Default based on schedule
            if [[ "${{ github.event.schedule }}" == "0 7 * * 1" ]]; then
              OPERATION="scale-out"
            else
              OPERATION="scale-in"
            fi
          fi
          
          # Set values based on operation
          if [[ "$OPERATION" == "scale-in" ]]; then
            MIN=0
            DESIRED=0
            MAX=0
          else
            MIN=3
            DESIRED=3
            MAX=10
          fi
          
          echo "min=$MIN" >> $GITHUB_OUTPUT
          echo "desired=$DESIRED" >> $GITHUB_OUTPUT
          echo "max=$MAX" >> $GITHUB_OUTPUT
          echo "operation=$OPERATION" >> $GITHUB_OUTPUT

      - name: Update platform-values.yaml
        run: |
          # Path to the platform-values.yaml file
          FILE_PATH="platform/prod/prod/gitops/iac-bootstrap/platform-values.yaml"
          
          # Update the values using sed
          sed -i "s/eksAsgMin:.*/eksAsgMin: ${{ steps.set-scaling.outputs.min }}/" $FILE_PATH
          sed -i "s/eksAsgDesired:.*/eksAsgDesired: ${{ steps.set-scaling.outputs.desired }}/" $FILE_PATH
          sed -i "s/eksAsgMax:.*/eksAsgMax: ${{ steps.set-scaling.outputs.max }}/" $FILE_PATH
          
          echo "Updated scaling parameters to: Min=${{ steps.set-scaling.outputs.min }}, Desired=${{ steps.set-scaling.outputs.desired }}, Max=${{ steps.set-scaling.outputs.max }}"
          echo "Operation: ${{ steps.set-scaling.outputs.operation }}"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto ${{ steps.set-scaling.outputs.operation }}: Update EKS scaling parameters"
          branch: feature/control-plane-ops
          file_pattern: platform/prod/prod/gitops/iac-bootstrap/platform-values.yaml
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@github.com
          commit_author: GitHub Actions <github-actions@github.com>
          # Use the PAT for authentication
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
