name: EKS Cluster Auto Scaling

# Add permissions block to elevate GITHUB_TOKEN permissions
permissions:
  contents: write

on:
  schedule:
    # Monday at 7am - Scale out
    - cron: '0 7 * * 1'
    # Friday at 8pm - Scale in
    - cron: '0 20 * * 5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-scaling-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: feature/control-plane-ops
          fetch-depth: 0
          # Using default GITHUB_TOKEN

      # Rest of the workflow remains the same
      
      - name: Set scaling parameters based on day and time
        id: set-scaling
        run: |
          # Same as your working workflow
          
      - name: Update platform-values.yaml
        run: |
          # Same as your working workflow
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto ${{ steps.set-scaling.outputs.operation }}: Update EKS scaling parameters"
          branch: feature/control-plane-ops
          file_pattern: platform/prod/prod/gitops/iac-bootstrap/platform-values.yaml
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@github.com
          commit_author: GitHub Actions <github-actions@github.com>
          # No token needed, uses GITHUB_TOKEN by default
